#mybatis配置信息
mybatis-plus:
  #对应mapper路劲
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
      platform: h2