spring:
  h2:
    console:
      enabled: true
  #数据库信息配置
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test
        username: user_write
        password: 111111
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test
        username: user_read
        password: 111111
    #      common:
    #        type: com.zaxxer.hikari.HikariDataSource
    #        driver-class-name: com.mysql.cj.jdbc.Driver
    #      master:
    #        type: com.zaxxer.hikari.HikariDataSource
    #        driver-class-name: org.h2.Driver
    ##        jdbc-url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;INIT=RUNSCRIPT FROM 'classpath:schema1.sql'\;RUNSCRIPT FROM 'classpath:data1.sql'
    #        jdbc-url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;INIT=RUNSCRIPT FROM 'classpath:schema1.sql'
    #        username: write
    #        password: 123456
    #      slave:
    #        type: com.zaxxer.hikari.HikariDataSource
    #        driver-class-name: org.h2.Driver
    #        jdbc-url: jdbc:h2:mem:test
    #        username: GUEST
    #        password: abc
    rules:
      readwrite-splitting:
        data-sources:
          readwrite:
            write-data-source-name: master
            read-data-source-names: slave
            load-balancer-name: round_robin
#  #数据库信息配置
#  datasource:
#    dynamic:
#      primary: master #设置默认的数据源或者数据源组,默认值即为master
#      strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
#      datasource:
#        master:
#          url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;INIT=RUNSCRIPT FROM 'classpath:schema1.sql'\;RUNSCRIPT FROM 'classpath:data1.sql'
#          username:
#          password:
#          driver-class-name: org.h2.Driver
#        slave:
#          url: jdbc:h2:mem:test
#          username: GUEST
#          password: abc
#          driver-class-name: org.h2.Driver

#mybatis配置信息
mybatis-plus:
  #对应mapper路劲
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      baomidou: debug