logging:
  level:
    com.viqbgrg.mybatisplus.mapper: debug
spring:
  h2:
    console:
      enabled: true
#配置枚举 支持通配符 * 或者 ; 分割
mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler