name: test
spring:
  profiles:
    active: dev
devName: defaultName

acme:
  user:
    username: xiaoming
    password: 123456


acme-bean:
  user:
    username: xiaoming
    password: 123456

test-string:
  value: hello