name: test
spring:
  profiles:
    active: dev
devName: defaultName

acme:
  user:
    username: xiaoming
    password: 123456


acme-bean:
  user:
    username: xiaoming
    password: 123456
  user1:
    username: zhangsan
    password: 654321

test-string:
  value: hello
user:
  a: test
  b: 22
value:
  name: haha
  size: 18
value1:
  name: hehe
  size: 20