CREATE USER IF NOT EXISTS GUEST PASSWORD '1111';
GRANT SELECT ON SCHEMA PUBLIC TO GUEST;
DROP TABLE IF EXISTS book;
CREATE TABLE book
(
    id   BIGINT(20)  NOT NULL COMMENT '主键ID',
    name varchar(20) not null comment '书名',
    PRIMARY KEY (id)
);