mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    root: WARN
    com:
      github:
        viqbgrg:
          springbootmybatisdemo:
            mapper: TRACE
