mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.github.viqbgrg.springbootmybatisdemo.domain

logging:
  level:
    root: WARN
    com:
      github:
        viqbgrg:
          springbootmybatisdemo:
            mapper: TRACE
